from enum import Enum

from .image import IMAGE_ANALYSIS
from .pitch_deck_prompts import (
    DECK_SHARED_SYSTEM_PROMPT, 
    PITCH_DECK_COMPETITORS_AND_DD_INSTRUCTION,
    PITCH_DECK_CORE_COMPANY_INSTRUCTION,
    PITCH_DECK_MARKET_SIZE_INSTRUCTION,
    PITCH_DECK_FOUNDERS_INSTRUCTION,
    PITCH_DECK_FINANCIALS_AND_ASK_INSTRUCTION,
    PITCH_DECK_SLIDE_SUMMARIES_INSTRUCTION,
    QUERY_PITCH_DECK_CONTENT
)
from .intak_layer import (
    INTAKE_SYSTEM_PROMPT,
    INTAKE_HUMAN_REQUEST_TEMPLATE,
    MARKET_SYSTEM_PROMPT,
    DEEP_RESEARCH_SYNTHESIZER_SYSTEM_PROMPT,
    DEEP_RESEARCH_SYNTHESIZER_USER_TEMPLATE,
)
from .market_prompts import (
    MARKET_PLANNER_SYSTEM_PROMPT,
    MARKET_SYNTHESIZER_SYSTEM_PROMPT,
    MARKET_RISK_ANALYST_SYSTEM_PROMPT,
)
from .competitor_prompts import (
    COMPETITOR_FINDER_PLANNER_SYSTEM_PROMPT,
    COMPETITOR_FINDER_SYNTHESIZER_SYSTEM_PROMPT,
    COMPETITOR_INVESTIGATOR_PLANNER_SYSTEM_PROMPT,
    COMPETITOR_INVESTIGATOR_SYNTHESIZER_SYSTEM_PROMPT,
    COMPETITIVE_RISK_ANALYST_SYSTEM_PROMPT,
)
from .founder_prompts import (
    FOUNDER_PROFILER_SYSTEM_PROMPT,
    FOUNDER_RISK_ANALYST_SYSTEM_PROMPT,
)
from .due_diligence_prompts import (
    DD_EXTRACTOR_SYSTEM_PROMPT,
    DD_LEGAL_VERIFIER_SYSTEM_PROMPT,
    DD_TRACTION_VERIFIER_SYSTEM_PROMPT,
    DD_PRESS_VERIFIER_SYSTEM_PROMPT,
    DD_SYNTHESIZER_SYSTEM_PROMPT,
)
from .report_prompts import (
    EXECUTIVE_SUMMARY_WRITER_PROMPT,
    MARKET_SECTION_WRITER_PROMPT,
    COMPETITOR_SECTION_WRITER_PROMPT,
    FOUNDER_SECTION_WRITER_PROMPT,
    DD_SECTION_WRITER_PROMPT,
    INVESTMENT_ADVOCATE_PROMPT,
    INVESTMENT_ADVERSARY_PROMPT,
    GROWTH_STRATEGIST_PROMPT,
    HAZARD_MITIGATOR_PROMPT,
    VENTURE_PARTNER_IC_PROMPT,
    MEMO_REVIEWER_PROMPT,
)

class PromptRegistry(str, Enum):
    """
    Central registry for all prompts used in the project.
    """

    image_analysis: str = IMAGE_ANALYSIS
    deck_system_prompt = DECK_SHARED_SYSTEM_PROMPT
    deck_company = PITCH_DECK_CORE_COMPANY_INSTRUCTION
    deck_market = PITCH_DECK_MARKET_SIZE_INSTRUCTION
    deck_founders = PITCH_DECK_FOUNDERS_INSTRUCTION
    deck_financials = PITCH_DECK_FINANCIALS_AND_ASK_INSTRUCTION
    deck_competitor = PITCH_DECK_COMPETITORS_AND_DD_INSTRUCTION
    deck_summary = PITCH_DECK_SLIDE_SUMMARIES_INSTRUCTION
    deck_query = QUERY_PITCH_DECK_CONTENT

    # Agent / Manager Prompts
    intake_system = INTAKE_SYSTEM_PROMPT
    intake_human = INTAKE_HUMAN_REQUEST_TEMPLATE
    market_system = MARKET_SYSTEM_PROMPT
    deep_research_synthesizer_system = DEEP_RESEARCH_SYNTHESIZER_SYSTEM_PROMPT
    deep_research_synthesizer_user = DEEP_RESEARCH_SYNTHESIZER_USER_TEMPLATE
    market_planner_system = MARKET_PLANNER_SYSTEM_PROMPT
    market_synthesizer_system = MARKET_SYNTHESIZER_SYSTEM_PROMPT
    market_risk_analyst_system = MARKET_RISK_ANALYST_SYSTEM_PROMPT
    competitor_finder_planner_system = COMPETITOR_FINDER_PLANNER_SYSTEM_PROMPT
    competitor_finder_synthesizer_system = COMPETITOR_FINDER_SYNTHESIZER_SYSTEM_PROMPT
    competitor_investigator_planner_system = COMPETITOR_INVESTIGATOR_PLANNER_SYSTEM_PROMPT
    competitor_investigator_synthesizer_system = COMPETITOR_INVESTIGATOR_SYNTHESIZER_SYSTEM_PROMPT
    competitive_risk_analyst_system = COMPETITIVE_RISK_ANALYST_SYSTEM_PROMPT
    founder_profiler_system = FOUNDER_PROFILER_SYSTEM_PROMPT
    founder_risk_analyst_system = FOUNDER_RISK_ANALYST_SYSTEM_PROMPT
    dd_extractor_system = DD_EXTRACTOR_SYSTEM_PROMPT
    dd_legal_verifier_system = DD_LEGAL_VERIFIER_SYSTEM_PROMPT
    dd_traction_verifier_system = DD_TRACTION_VERIFIER_SYSTEM_PROMPT
    dd_press_verifier_system = DD_PRESS_VERIFIER_SYSTEM_PROMPT
    dd_synthesizer_system = DD_SYNTHESIZER_SYSTEM_PROMPT

    # Report / Memo Prompts
    executive_summary_writer_system = EXECUTIVE_SUMMARY_WRITER_PROMPT
    market_section_writer_system = MARKET_SECTION_WRITER_PROMPT
    competitor_section_writer_system = COMPETITOR_SECTION_WRITER_PROMPT
    founder_section_writer_system = FOUNDER_SECTION_WRITER_PROMPT
    dd_section_writer_system = DD_SECTION_WRITER_PROMPT
    investment_advocate_system = INVESTMENT_ADVOCATE_PROMPT
    investment_adversary_system = INVESTMENT_ADVERSARY_PROMPT
    growth_strategist_system = GROWTH_STRATEGIST_PROMPT
    hazard_mitigator_system = HAZARD_MITIGATOR_PROMPT
    venture_partner_ic_system = VENTURE_PARTNER_IC_PROMPT
    memo_reviewer_system = MEMO_REVIEWER_PROMPT
